import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{js,ts,jsx,tsx,mdx}", "./components/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e1e3e4",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d8e2ff",
        "surface-bright": "#f8fafb",
        "outline-variant": "#c1c6d6",
        "on-secondary-fixed": "#001a41",
        "secondary-fixed": "#d8e2ff",
        "on-primary": "#ffffff",
        "background": "#f8fafb",
        "surface-dim": "#d8dadb",
        "inverse-on-surface": "#eff1f2",
        "surface-container-low": "#f2f4f5",
        "error-container": "#ffdad6",
        "tertiary": "#9e4300",
        "primary-container": "#1a73e8",
        "surface-tint": "#005bc0",
        "primary-fixed-dim": "#adc7ff",
        "primary": "#005bbf",
        "on-primary-fixed-variant": "#004493",
        "secondary": "#475e8c",
        "on-primary-fixed": "#001a41",
        "on-primary-container": "#ffffff",
        "on-background": "#191c1d",
        "surface-container-highest": "#e1e3e4",
        "surface": "#f8fafb",
        "on-surface": "#191c1d",
        "on-secondary-container": "#3d5481",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#afc7fb",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#414754",
        "error": "#ba1a1a",
        "secondary-container": "#b2c9fe",
        "inverse-primary": "#adc7ff",
        "inverse-surface": "#2e3132",
        "on-error": "#ffffff",
        "outline": "#727785",
        "surface-container": "#eceeef",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
export default config;
